/* ═══════════════════════════════════════════════════════════
   Personas — 3 seeded user profiles for demo/testing.
   Each persona defines a profile that gets run through the
   same completeOnboarding() pipeline as a real user.
   ═══════════════════════════════════════════════════════════ */

export const PERSONAS = [
  {
    id: 'daniel',
    name: 'Daniel',
    tag: 'RECOMP',
    tagColor: '#FF6E50',
    description: '28M, intermediate lifter, recomp + fat loss',
    profile: {
      name: 'Daniel Lacayo',
      sex: 'male',
      weight: 82.1,
      height: 180,
      birthYear: 1996,
      birthMonth: 3,
      activityLevel: 'moderate',
      bodyFat: '18-23%',
      exerciseFreq: '4-6',
      goal: 'recomp',
      goals: ['recomposition', 'fat_loss'],
      equipment: 'full_gym',
      availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      liftingExp: 'intermediate',
      cardioExp: 'beginner',
      dietary: [],
      injuries: [],
      focusMuscles: [],
    },
    checkins: [
      { date: '06 Jul', weight: 82.1, bf: 20.1, delta: -0.4 },
      { date: '29 Jun', weight: 82.5, bf: 20.4, delta: -0.3 },
      { date: '22 Jun', weight: 82.8, bf: 20.6, delta: -0.5 },
      { date: '15 Jun', weight: 83.3, bf: 20.9, delta: -0.2 },
    ],
  },
  {
    id: 'maya',
    name: 'Maya',
    tag: 'FAT LOSS',
    tagColor: '#4ade80',
    description: '31F, beginner, fat loss + cook more',
    profile: {
      name: 'Maya Chen',
      sex: 'female',
      weight: 68.5,
      height: 165,
      birthYear: 1995,
      birthMonth: 8,
      activityLevel: 'light',
      bodyFat: '28-33%',
      exerciseFreq: '1-3',
      goal: 'fat_loss',
      goals: ['fat_loss', 'cook_more'],
      equipment: 'home_basic',
      availableDays: ['Mon', 'Wed', 'Fri'],
      liftingExp: 'beginner',
      cardioExp: 'beginner',
      dietary: ['Gluten Free'],
      injuries: ['Knees'],
      focusMuscles: [],
    },
    checkins: [
      { date: '06 Jul', weight: 68.5, bf: 30.2, delta: -0.6 },
      { date: '29 Jun', weight: 69.1, bf: 30.8, delta: -0.4 },
      { date: '22 Jun', weight: 69.5, bf: 31.1, delta: -0.3 },
    ],
  },
  {
    id: 'kai',
    name: 'Kai',
    tag: 'HYPERTROPHY',
    tagColor: '#60a5fa',
    description: '24M, advanced, hypertrophy + strength',
    profile: {
      name: 'Kai Rivera',
      sex: 'male',
      weight: 93.0,
      height: 188,
      birthYear: 2002,
      birthMonth: 1,
      activityLevel: 'very_active',
      bodyFat: '13-17%',
      exerciseFreq: '4-6',
      goal: 'hypertrophy',
      goals: ['hypertrophy', 'max_strength'],
      equipment: 'full_gym',
      availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
      liftingExp: 'advanced',
      cardioExp: 'intermediate',
      dietary: ['Dairy Free'],
      injuries: [],
      focusMuscles: [],
    },
    checkins: [
      { date: '06 Jul', weight: 93.0, bf: 14.8, delta: 0.3 },
      { date: '29 Jun', weight: 92.7, bf: 14.6, delta: 0.4 },
      { date: '22 Jun', weight: 92.3, bf: 14.5, delta: 0.2 },
      { date: '15 Jun', weight: 92.1, bf: 14.7, delta: 0.3 },
      { date: '08 Jun', weight: 91.8, bf: 14.9, delta: 0.2 },
    ],
  },
]
